### ISSUE TITLE
react native purchases is not working in react native latest release 0.74 

### ISSUE THREAD

**Issue by stack-Rambo** [RevenueCat/react-native-purchases#1002]
This is the error i got while implementing Revenue cat SDK in react native latest version 0.74
 ERROR  Error configuring Purchases: [TypeError: _reactNativePurchases.default.setup is not a function (it is undefined)]
 This is the simple code i used .
 step1: downladed the package : npx install react-native-purchases
 step2: wrote this code in App.js file in React native and the above error message is displayed
 step3: code for APP.js
 import React,{useEffect} from 'react';
import { StatusBar } from 'react-native';
import Purchases from 'react-native-purchases';
import Router from './src/Route';
import { API_KEY } from './src/constants';

const App = () => {
  useEffect(() => {
    const configurePurchases = async () => {
      Purchases.setLogLevel(Purchases.LOG_LEVEL.DEBUG);
      try {
        
        await Purchases.setup(API_KEY, null, false, false);
      } catch (error) {
        console.error('Error configuring Purchases:', error);
      }
    };

    configurePurchases();
  }, []);

  return (
    <>
      <StatusBar barStyle="light-content" />
      <Router />
    </>
  );
};

export default App;

**Comment by RCGitBot** [comment]
👀 We've just linked this [issue to our internal tracker](https://revenuecat.zendesk.com/agent/tickets/40894) and notified the team. Thank you for reporting, we're checking this out!

**Comment by jameslporter** [comment]
Seems fine for me on Android build but fails on iOS. Expo SDK 51.0.7

**Comment by rikur** [comment]
@stack-Rambo you must have upgraded from one major version to another, and hit some breaking changes.

There's no `Purchases.setup()` anymore, try:

```
Purchases.configure({ apiKey })
```

**Comment by Jethro87** [comment]
@stack-Rambo As @rikur said, please use `configure` instead of `setup`. [Documentation](https://www.revenuecat.com/docs/getting-started/configuring-sdk).
